services:
  client:
    build:
      context: ./client
    image: vikrampatel/docify_client
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env

  server:
    build:
      context: ./server
    image: vikrampatel/docify_server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env

  auth:
    build:
      context: ./auth
    image: vikrampatel/docify_auth
    ports:
      - "5000:5000"
    env_file:
      - ./auth/.env
